[package]
name = "kernel-wrap"
version = "0.1.0"
edition = "2024"

[dependencies]
#bootloader = "0.11"
bootloader_api = "0.11.9"

[dependencies.font8x8]
version = "0.2.5"
default-features = false
features = ["unicode"]
